set -e                  # exit on error
set -o pipefail         # exit on pipeline error
set -u                  # treat unset variable as error

print_ok "Reconfiguring locales..."
# Restore the full SUPPORTED list in case update-locale narrowed it via debconf.
cat /usr/share/i18n/SUPPORTED > /etc/locale.gen
dpkg-reconfigure locales
judge "Reconfigure locales"

print_ok "Configuring locales to $DEFAULT_LANG..."

cat << EOF > /etc/default/locale
#  File generated by update-locale
LANG="$DEFAULT_LANG"
EOF
judge "Configure /etc/default/locale"

# /etc/skel/.pam_environment is intentionally omitted.
# Modern GNOME (>= 40) ignores this file for security reasons — it permits
# arbitrary env-var injection at login.  Locale is handled by
# /etc/default/locale (via pam_env.so) and accountsservice instead.

# This is actually setting on the system clock, not the timezone. Do not use this command:
# > timedatectl set-timezone $TIMEZONE
# To set the timezone for the new OS being built (In chroot environment), use the following command:

# If TIMEZONE was not set, exit.
if [ -z "$TIMEZONE" ]; then
    print_error "Error: TIMEZONE is not set."
    exit 1
fi

if [ ! -f /usr/share/zoneinfo/$TIMEZONE ]; then
    print_error "Error: /usr/share/zoneinfo/$TIMEZONE not found."
    exit 1
fi

print_ok "Configuring /etc/timezone to $TIMEZONE..."
echo $TIMEZONE > /etc/timezone
judge "Configure /etc/timezone"

print_ok "Configuring /etc/localtime to $TIMEZONE..."
rm -f /etc/localtime
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
judge "Configure /etc/timezone and /etc/localtime"


