set -e                  # exit on error
set -o pipefail         # exit on pipeline error
set -u                  # treat unset variable as error

print_ok "Reconfiguring locales..."
# Restore the full SUPPORTED list in case update-locale narrowed it via debconf.
cat /usr/share/i18n/SUPPORTED > /etc/locale.gen
dpkg-reconfigure locales
judge "Reconfigure locales"

# print_ok "Locking locales to $DEFAULT_LANG..."

# Installed system default locale.
# This is what the ISO ships as the out-of-box system language (login screen, new user sessions).
# Ubiquity can still change it at install time when the user picks a different language.
#
# Common examples:
#   DEFAULT_LANG="en_US.UTF-8"    # English (default)
#   DEFAULT_LANG="zh_CN.UTF-8"    # Simplified Chinese
#   DEFAULT_LANG="zh_TW.UTF-8"    # Traditional Chinese (Taiwan)
#   DEFAULT_LANG="zh_HK.UTF-8"    # Traditional Chinese (Hong Kong)
#   DEFAULT_LANG="ja_JP.UTF-8"    # Japanese
#   DEFAULT_LANG="ko_KR.UTF-8"    # Korean
#   DEFAULT_LANG="vi_VN.UTF-8"    # Vietnamese
#   DEFAULT_LANG="th_TH.UTF-8"    # Thai
#   DEFAULT_LANG="de_DE.UTF-8"    # German
#   DEFAULT_LANG="fr_FR.UTF-8"    # French
#   DEFAULT_LANG="es_ES.UTF-8"    # Spanish
#   DEFAULT_LANG="ru_RU.UTF-8"    # Russian
#   DEFAULT_LANG="it_IT.UTF-8"    # Italian
#   DEFAULT_LANG="pt_BR.UTF-8"    # Portuguese (Brazil)
#   DEFAULT_LANG="pt_PT.UTF-8"    # Portuguese (Portugal)
#   DEFAULT_LANG="ar_SA.UTF-8"    # Arabic
#   DEFAULT_LANG="nl_NL.UTF-8"    # Dutch
#   DEFAULT_LANG="sv_SE.UTF-8"    # Swedish
#   DEFAULT_LANG="pl_PL.UTF-8"    # Polish
#   DEFAULT_LANG="tr_TR.UTF-8"    # Turkish
#   DEFAULT_LANG="ro_RO.UTF-8"    # Romanian
# cat << EOF > /etc/default/locale
# #  File generated by update-locale
# LANG="$DEFAULT_LANG"
# EOF
# judge "Configure /etc/default/locale"

# If TIMEZONE was not set, exit.
if [ -z "$TIMEZONE" ]; then
    print_error "Error: TIMEZONE is not set."
    exit 1
fi

if [ ! -f /usr/share/zoneinfo/$TIMEZONE ]; then
    print_error "Error: /usr/share/zoneinfo/$TIMEZONE not found."
    exit 1
fi

print_ok "Configuring /etc/timezone to $TIMEZONE..."
echo $TIMEZONE > /etc/timezone
judge "Configure /etc/timezone"

print_ok "Configuring /etc/localtime to $TIMEZONE..."
rm -f /etc/localtime
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
judge "Configure /etc/timezone and /etc/localtime"


